const METADATA_FIELDS = {
  POSTING_DATE: "POSTING_DATE",
  UPDATED_DATE: "UPDATED_DATE",
  EXPIRY_DATE: "EXPIRY_DATE",
  END_DATE: "END_DATE",
  SUBMITTER: "SUBMITTER",
};

module.exports = {
  METADATA_FIELDS,
};
