{{- $random_postgres_user := randAlphaNum 10 }}
{{- $random_postgres_password := randAlphaNum 32 }}
{{- $random_postgres_admin_password := randAlphaNum 32 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgres-secret" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    component: {{ .Values.postgres.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  POSTGRESQL_USER: user_{{ $random_postgres_user }}
  POSTGRESQL_PASSWORD: {{ $random_postgres_password | quote }}
  POSTGRESQL_ADMIN_PASSWORD: {{ $random_postgres_admin_password | quote }}
  POSTGRESQL_DATABASE: cms
{{- end -}}