cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth
  publicUrl: https://bcparks.ca
  staffPortalUrl: https://staff.bcparks.ca

images:
  strapi:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  maintenance:
    tag: prod
  etl:
    tag: prod
  scheduler:
    tag: prod

cms:
  resources:
    requests:
      cpu: 175m
      memory: 625Mi

  env:
    environment: prod
    externalUrl: https://cms.bcparks.ca
    cacheTtl: "600000"

  hpa:
    minReplicas: 2
    maxReplicas: 4
    cpuUtilizationThreshold: 65

crunchy:
  instanceName: crunchy-postgres

public:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

  hpa:
    minReplicas: 2
    maxReplicas: 8
    cpuUtilizationThreshold: 35

etl:
  env:
    parkNamesApi: https://data.bcparks.ca/api/parks/names?status=established

scheduler:
  env:
    emailEnabled: true
