cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth
  publicUrl: https://dev.bcparks.ca
  staffPortalUrl: https://dev-staff.bcparks.ca
  recSpaceApiUrl: https://dv5oa6g5xh0tq.cloudfront.net

cms:
  env:
    environment: dev
    externalUrl: https://dev-cms.bcparks.ca

crunchy:
  instanceName: crunchy-postgres

scheduler:
  env:
    emailEnabled: true
    emailRecipient: manuji@oxd.com,mike@oxd.com
    emailRecipientWhitelist: manuji@oxd.com,mike@oxd.com
    recSpaceKeycloakTokenUrl: https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token
    recSpaceKeycloakClientId: testing-act-integration-6456

etl:
  enabled: false
