cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth
  publicUrl: https://test.bcparks.ca
  staffPortalUrl: https://test-staff.bcparks.ca

images:
  strapi:
    tag: test
  admin:
    tag: test
  public:
    tag: test
  maintenance:
    tag: test
  etl:
    tag: test
  scheduler:
    tag: test

cms:
  env:
    environment: test
    externalUrl: https://test-cms.bcparks.ca

crunchy:
  instanceName: crunchy-postgres

scheduler:
  env:
    emailEnabled: true
