import "@bcgov/bootstrap-theme/dist/css/bootstrap-theme.min.css"
import "jquery/dist/jquery.slim"
import "bootstrap/dist/js/bootstrap.bundle"
import "@fortawesome/fontawesome-free/css/all.min.css"
import "./src/styles/style.scss"