fullnameOverride: crunchy-postgres-alpha

postgresVersion: 17

instances:
  replicas: 1
  dataVolumeClaimSpec:
    storage: 2Gi
  requests:
    cpu: 100m

pgBackRest:
  repos:
    volume:
      storage: 2Gi

proxy:
  pgBouncer:
    replicas: 1

pgmonitor:
  namespace: c1643c #The high level namespace of your project without the -tools -dev, etc part.
