{{- if not (lookup "v1" "Secret" .Release.Namespace (include "bcparks_etl_secret" .)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "bcparks_etl_secret" . }}
  labels:
    component: {{ .Values.etl.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  STRAPI_API_TOKEN: ""
  PARK_NAMES_API_KEY: ""
  REC_SPACE_KEYCLOAK_CLIENT_SECRET: ""
{{- end -}}
