{{- if or .Values.cms.env.externalUrl .Values.cluster.publicUrl }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-vanity-tls-reader
  labels:
    component: vanity
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-vanity-tls-reader
subjects:
  - kind: ServiceAccount
    name: router
    namespace: openshift-ingress
{{- end }}
