name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be promoted to PROD"
        required: true

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-tools
  ENVIRONMENT: prod
  NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.releaseTag }}

      - name: Tag not found
        if: ${{ failure() }}
        run: |
          echo "::error::Git Tag not found, please double check input"
          exit 1

      - name: Set env
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_GOLD_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_GOLD_SERVICE_TOKEN }}

      - name: TESTING Create OpenShift secret
        run: |
          oc create secret generic test-access-secret --from-literal=TEST_REPO_ACCESS_TOKEN="${{ secrets.REPO_ACCESS_TOKEN }}"
