name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be promoted to PROD"
        required: true

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-tools
  ENVIRONMENT: prod
  NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Attempt to checkout tag
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.releaseTag }}

      - name: Tag not found
        if: ${{ failure() }}
        run: |
          echo "::error::Git Tag not found, please double check input"
          exit 1

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.16"
          skip_cache: true

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_GOLD_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_GOLD_SERVICE_TOKEN }}

      - name: Tag Prod images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public-builder-main:${{ github.event.inputs.releaseTag }} public-builder-main:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag strapi-main:${{ github.event.inputs.releaseTag }} strapi-main:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag maintenance-main:${{ github.event.inputs.releaseTag }} maintenance-main:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag etl-main:${{ github.event.inputs.releaseTag }} etl-main:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag scheduler-main:${{ github.event.inputs.releaseTag }} scheduler-main:${{ env.ENVIRONMENT }}

      - name: Trigger Gatsby static build workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          BUILD_ENV: ${{ env.ENVIRONMENT }}
        run: |
          # workflow_dispatch runs the publish-gatsby.yaml from the triggering branch
          gh workflow run publish-gatsby.yaml --repo "$GITHUB_REPOSITORY" \
            --ref "$BRANCH" -f branchName="$BRANCH" -f buildEnv="$BUILD_ENV"

      - name: Trigger new rollout
        run: |
          oc -n ${{ env.NAMESPACE }} rollout restart deployment main-cms
          oc -n ${{ env.NAMESPACE }} rollout restart deployment main-maintenance
          oc -n ${{ env.NAMESPACE }} rollout restart deployment main-scheduler
