name: Deploy Alpha to Alpha-Test

on:
  workflow_dispatch

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-tools
  ENVIRONMENT: test
  NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.16"
          skip_cache: true

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_GOLD_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_GOLD_SERVICE_TOKEN }}

      - name: Tag Test images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public-builder-alpha:latest public-builder-alpha:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag strapi-alpha:latest strapi-alpha:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag maintenance-alpha:latest maintenance-alpha:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag etl-alpha:latest etl-alpha:${{ env.ENVIRONMENT }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag scheduler-alpha:latest scheduler-alpha:${{ env.ENVIRONMENT }}

      - name: Trigger Gatsby static build workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: alpha
          BUILD_ENV: ${{ env.ENVIRONMENT }}
        run: |
          # workflow_dispatch runs the publish-gatsby.yaml from the triggering branch
          gh workflow run publish-gatsby.yaml --repo "$GITHUB_REPOSITORY" \
            --ref "$BRANCH" -f branchName="$BRANCH" -f buildEnv="$BUILD_ENV"

      - name: Trigger new rollout
        run: |
          oc -n ${{ env.NAMESPACE }} rollout restart deployment alpha-cms
          oc -n ${{ env.NAMESPACE }} rollout restart deployment alpha-maintenance
          oc -n ${{ env.NAMESPACE }} rollout restart deployment alpha-scheduler
