name: Tag image on Git Tag Push

on:
  push:
    tags:
      - "*"

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-tools
  NAMESPACE: ${{ secrets.OPENSHIFT_GOLD_LICENSE_PLATE }}-test

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_GOLD_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_GOLD_SERVICE_TOKEN }}

      - name: Tag images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public-builder-main:${{ env.SHORT_SHA }} public-builder-main:${{ env.RELEASE_VERSION }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag strapi-main:${{ env.SHORT_SHA }} strapi-main:${{ env.RELEASE_VERSION }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag maintenance-main:${{ env.SHORT_SHA }} maintenance-main:${{ env.RELEASE_VERSION }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag etl-main:${{ env.SHORT_SHA }} etl-main:${{ env.RELEASE_VERSION }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag scheduler-main:${{ env.SHORT_SHA }} scheduler-main:${{ env.RELEASE_VERSION }}

      - name: Delete images tags with commit hash
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d public-builder-main:${{ env.SHORT_SHA }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d strapi-main:${{ env.SHORT_SHA }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d maintenance-main:${{ env.SHORT_SHA }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d etl-main:${{ env.SHORT_SHA }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d scheduler-main:${{ env.SHORT_SHA }}
